version: 2

jobs:
  build:
    docker:
      - image: golang:1.17-bullseye
    working_directory: /go/src/github.com/kazegusuri/grpcurl
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            make dep

      - run:
          name: run tests
          command: |
            make test
      - run:
          name: run build
          command: |
            make build
