// Code generated by protoc-gen-go.
// source: testdata/everything.proto
// DO NOT EDIT!

package testdata

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type NumericEnum int32

const (
	NumericEnum_ZERO NumericEnum = 0
	NumericEnum_ONE  NumericEnum = 1
	NumericEnum_TWO  NumericEnum = 2
)

var NumericEnum_name = map[int32]string{
	0: "ZERO",
	1: "ONE",
	2: "TWO",
}
var NumericEnum_value = map[string]int32{
	"ZERO": 0,
	"ONE":  1,
	"TWO":  2,
}

func (x NumericEnum) String() string {
	return proto.EnumName(NumericEnum_name, int32(x))
}
func (NumericEnum) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type AliasedEnum int32

const (
	AliasedEnum_UNKNOWN AliasedEnum = 0
	AliasedEnum_STARTED AliasedEnum = 1
	AliasedEnum_RUNNING AliasedEnum = 1
)

var AliasedEnum_name = map[int32]string{
	0: "UNKNOWN",
	1: "STARTED",
	// Duplicate value: 1: "RUNNING",
}
var AliasedEnum_value = map[string]int32{
	"UNKNOWN": 0,
	"STARTED": 1,
	"RUNNING": 1,
}

func (x AliasedEnum) String() string {
	return proto.EnumName(AliasedEnum_name, int32(x))
}
func (AliasedEnum) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type EnumMessage_Nested int32

const (
	EnumMessage_UNKNOWN   EnumMessage_Nested = 0
	EnumMessage_PENDING   EnumMessage_Nested = 1
	EnumMessage_COMPLETED EnumMessage_Nested = 2
)

var EnumMessage_Nested_name = map[int32]string{
	0: "UNKNOWN",
	1: "PENDING",
	2: "COMPLETED",
}
var EnumMessage_Nested_value = map[string]int32{
	"UNKNOWN":   0,
	"PENDING":   1,
	"COMPLETED": 2,
}

func (x EnumMessage_Nested) String() string {
	return proto.EnumName(EnumMessage_Nested_name, int32(x))
}
func (EnumMessage_Nested) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{3, 0} }

type SimpleMessage struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue" json:"string_value,omitempty"`
	BoolValue   bool   `protobuf:"varint,2,opt,name=bool_value,json=boolValue" json:"bool_value,omitempty"`
}

func (m *SimpleMessage) Reset()                    { *m = SimpleMessage{} }
func (m *SimpleMessage) String() string            { return proto.CompactTextString(m) }
func (*SimpleMessage) ProtoMessage()               {}
func (*SimpleMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *SimpleMessage) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *SimpleMessage) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

type NumberMessage struct {
	FloatValue    float32 `protobuf:"fixed32,1,opt,name=float_value,json=floatValue" json:"float_value,omitempty"`
	DoubleValue   float64 `protobuf:"fixed64,2,opt,name=double_value,json=doubleValue" json:"double_value,omitempty"`
	Int32Value    int32   `protobuf:"varint,3,opt,name=int32_value,json=int32Value" json:"int32_value,omitempty"`
	Int64Value    int64   `protobuf:"varint,4,opt,name=int64_value,json=int64Value" json:"int64_value,omitempty"`
	Uint32Value   uint32  `protobuf:"varint,5,opt,name=uint32_value,json=uint32Value" json:"uint32_value,omitempty"`
	Uint64Value   uint64  `protobuf:"varint,6,opt,name=uint64_value,json=uint64Value" json:"uint64_value,omitempty"`
	Sint32Value   int32   `protobuf:"zigzag32,7,opt,name=sint32_value,json=sint32Value" json:"sint32_value,omitempty"`
	Sint64Value   int64   `protobuf:"zigzag64,8,opt,name=sint64_value,json=sint64Value" json:"sint64_value,omitempty"`
	Fixed32Value  uint32  `protobuf:"fixed32,9,opt,name=fixed32_value,json=fixed32Value" json:"fixed32_value,omitempty"`
	Fixed64Value  uint64  `protobuf:"fixed64,10,opt,name=fixed64_value,json=fixed64Value" json:"fixed64_value,omitempty"`
	Sfixed32Value int32   `protobuf:"fixed32,11,opt,name=sfixed32_value,json=sfixed32Value" json:"sfixed32_value,omitempty"`
	Sfixed64Value int64   `protobuf:"fixed64,12,opt,name=sfixed64_value,json=sfixed64Value" json:"sfixed64_value,omitempty"`
}

func (m *NumberMessage) Reset()                    { *m = NumberMessage{} }
func (m *NumberMessage) String() string            { return proto.CompactTextString(m) }
func (*NumberMessage) ProtoMessage()               {}
func (*NumberMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *NumberMessage) GetFloatValue() float32 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *NumberMessage) GetDoubleValue() float64 {
	if m != nil {
		return m.DoubleValue
	}
	return 0
}

func (m *NumberMessage) GetInt32Value() int32 {
	if m != nil {
		return m.Int32Value
	}
	return 0
}

func (m *NumberMessage) GetInt64Value() int64 {
	if m != nil {
		return m.Int64Value
	}
	return 0
}

func (m *NumberMessage) GetUint32Value() uint32 {
	if m != nil {
		return m.Uint32Value
	}
	return 0
}

func (m *NumberMessage) GetUint64Value() uint64 {
	if m != nil {
		return m.Uint64Value
	}
	return 0
}

func (m *NumberMessage) GetSint32Value() int32 {
	if m != nil {
		return m.Sint32Value
	}
	return 0
}

func (m *NumberMessage) GetSint64Value() int64 {
	if m != nil {
		return m.Sint64Value
	}
	return 0
}

func (m *NumberMessage) GetFixed32Value() uint32 {
	if m != nil {
		return m.Fixed32Value
	}
	return 0
}

func (m *NumberMessage) GetFixed64Value() uint64 {
	if m != nil {
		return m.Fixed64Value
	}
	return 0
}

func (m *NumberMessage) GetSfixed32Value() int32 {
	if m != nil {
		return m.Sfixed32Value
	}
	return 0
}

func (m *NumberMessage) GetSfixed64Value() int64 {
	if m != nil {
		return m.Sfixed64Value
	}
	return 0
}

type NestedMessage struct {
	NestedValue          *NestedMessage_Nested   `protobuf:"bytes,1,opt,name=nested_value,json=nestedValue" json:"nested_value,omitempty"`
	RepeatedNestedValues []*NestedMessage_Nested `protobuf:"bytes,2,rep,name=repeated_nested_values,json=repeatedNestedValues" json:"repeated_nested_values,omitempty"`
}

func (m *NestedMessage) Reset()                    { *m = NestedMessage{} }
func (m *NestedMessage) String() string            { return proto.CompactTextString(m) }
func (*NestedMessage) ProtoMessage()               {}
func (*NestedMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *NestedMessage) GetNestedValue() *NestedMessage_Nested {
	if m != nil {
		return m.NestedValue
	}
	return nil
}

func (m *NestedMessage) GetRepeatedNestedValues() []*NestedMessage_Nested {
	if m != nil {
		return m.RepeatedNestedValues
	}
	return nil
}

type NestedMessage_Nested struct {
	Int32Value  int32  `protobuf:"varint,1,opt,name=int32_value,json=int32Value" json:"int32_value,omitempty"`
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue" json:"string_value,omitempty"`
}

func (m *NestedMessage_Nested) Reset()                    { *m = NestedMessage_Nested{} }
func (m *NestedMessage_Nested) String() string            { return proto.CompactTextString(m) }
func (*NestedMessage_Nested) ProtoMessage()               {}
func (*NestedMessage_Nested) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 0} }

func (m *NestedMessage_Nested) GetInt32Value() int32 {
	if m != nil {
		return m.Int32Value
	}
	return 0
}

func (m *NestedMessage_Nested) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

type EnumMessage struct {
	NumericEnumValue          NumericEnum          `protobuf:"varint,1,opt,name=numeric_enum_value,json=numericEnumValue,enum=grpcurl.test.NumericEnum" json:"numeric_enum_value,omitempty"`
	RepeatedNumericEnumValues []NumericEnum        `protobuf:"varint,2,rep,packed,name=repeated_numeric_enum_values,json=repeatedNumericEnumValues,enum=grpcurl.test.NumericEnum" json:"repeated_numeric_enum_values,omitempty"`
	AliasedEnumValue          AliasedEnum          `protobuf:"varint,3,opt,name=aliased_enum_value,json=aliasedEnumValue,enum=grpcurl.test.AliasedEnum" json:"aliased_enum_value,omitempty"`
	NestedEnumValue           EnumMessage_Nested   `protobuf:"varint,4,opt,name=nested_enum_value,json=nestedEnumValue,enum=grpcurl.test.EnumMessage_Nested" json:"nested_enum_value,omitempty"`
	RepeatedNestedEnumValues  []EnumMessage_Nested `protobuf:"varint,5,rep,packed,name=repeated_nested_enum_values,json=repeatedNestedEnumValues,enum=grpcurl.test.EnumMessage_Nested" json:"repeated_nested_enum_values,omitempty"`
}

func (m *EnumMessage) Reset()                    { *m = EnumMessage{} }
func (m *EnumMessage) String() string            { return proto.CompactTextString(m) }
func (*EnumMessage) ProtoMessage()               {}
func (*EnumMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *EnumMessage) GetNumericEnumValue() NumericEnum {
	if m != nil {
		return m.NumericEnumValue
	}
	return NumericEnum_ZERO
}

func (m *EnumMessage) GetRepeatedNumericEnumValues() []NumericEnum {
	if m != nil {
		return m.RepeatedNumericEnumValues
	}
	return nil
}

func (m *EnumMessage) GetAliasedEnumValue() AliasedEnum {
	if m != nil {
		return m.AliasedEnumValue
	}
	return AliasedEnum_UNKNOWN
}

func (m *EnumMessage) GetNestedEnumValue() EnumMessage_Nested {
	if m != nil {
		return m.NestedEnumValue
	}
	return EnumMessage_UNKNOWN
}

func (m *EnumMessage) GetRepeatedNestedEnumValues() []EnumMessage_Nested {
	if m != nil {
		return m.RepeatedNestedEnumValues
	}
	return nil
}

type OneofMessage struct {
	// Types that are valid to be assigned to OneofValue:
	//	*OneofMessage_Int32Value
	//	*OneofMessage_StringValue
	OneofValue isOneofMessage_OneofValue `protobuf_oneof:"oneof_value"`
}

func (m *OneofMessage) Reset()                    { *m = OneofMessage{} }
func (m *OneofMessage) String() string            { return proto.CompactTextString(m) }
func (*OneofMessage) ProtoMessage()               {}
func (*OneofMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type isOneofMessage_OneofValue interface {
	isOneofMessage_OneofValue()
}

type OneofMessage_Int32Value struct {
	Int32Value int32 `protobuf:"varint,1,opt,name=int32_value,json=int32Value,oneof"`
}
type OneofMessage_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,oneof"`
}

func (*OneofMessage_Int32Value) isOneofMessage_OneofValue()  {}
func (*OneofMessage_StringValue) isOneofMessage_OneofValue() {}

func (m *OneofMessage) GetOneofValue() isOneofMessage_OneofValue {
	if m != nil {
		return m.OneofValue
	}
	return nil
}

func (m *OneofMessage) GetInt32Value() int32 {
	if x, ok := m.GetOneofValue().(*OneofMessage_Int32Value); ok {
		return x.Int32Value
	}
	return 0
}

func (m *OneofMessage) GetStringValue() string {
	if x, ok := m.GetOneofValue().(*OneofMessage_StringValue); ok {
		return x.StringValue
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*OneofMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _OneofMessage_OneofMarshaler, _OneofMessage_OneofUnmarshaler, _OneofMessage_OneofSizer, []interface{}{
		(*OneofMessage_Int32Value)(nil),
		(*OneofMessage_StringValue)(nil),
	}
}

func _OneofMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*OneofMessage)
	// oneof_value
	switch x := m.OneofValue.(type) {
	case *OneofMessage_Int32Value:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Int32Value))
	case *OneofMessage_StringValue:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.StringValue)
	case nil:
	default:
		return fmt.Errorf("OneofMessage.OneofValue has unexpected type %T", x)
	}
	return nil
}

func _OneofMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*OneofMessage)
	switch tag {
	case 1: // oneof_value.int32_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.OneofValue = &OneofMessage_Int32Value{int32(x)}
		return true, err
	case 2: // oneof_value.string_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.OneofValue = &OneofMessage_StringValue{x}
		return true, err
	default:
		return false, nil
	}
}

func _OneofMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*OneofMessage)
	// oneof_value
	switch x := m.OneofValue.(type) {
	case *OneofMessage_Int32Value:
		n += proto.SizeVarint(1<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Int32Value))
	case *OneofMessage_StringValue:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.StringValue)))
		n += len(x.StringValue)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type MapMessage struct {
	MapValue          map[string]NumericEnum    `protobuf:"bytes,1,rep,name=map_value,json=mapValue" json:"map_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=grpcurl.test.NumericEnum"`
	MappedStringValue map[string]string         `protobuf:"bytes,2,rep,name=mapped_string_value,json=mappedStringValue" json:"mapped_string_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MappedNestedValue map[string]*NestedMessage `protobuf:"bytes,3,rep,name=mapped_nested_value,json=mappedNestedValue" json:"mapped_nested_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *MapMessage) Reset()                    { *m = MapMessage{} }
func (m *MapMessage) String() string            { return proto.CompactTextString(m) }
func (*MapMessage) ProtoMessage()               {}
func (*MapMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *MapMessage) GetMapValue() map[string]NumericEnum {
	if m != nil {
		return m.MapValue
	}
	return nil
}

func (m *MapMessage) GetMappedStringValue() map[string]string {
	if m != nil {
		return m.MappedStringValue
	}
	return nil
}

func (m *MapMessage) GetMappedNestedValue() map[string]*NestedMessage {
	if m != nil {
		return m.MappedNestedValue
	}
	return nil
}

func init() {
	proto.RegisterType((*SimpleMessage)(nil), "grpcurl.test.SimpleMessage")
	proto.RegisterType((*NumberMessage)(nil), "grpcurl.test.NumberMessage")
	proto.RegisterType((*NestedMessage)(nil), "grpcurl.test.NestedMessage")
	proto.RegisterType((*NestedMessage_Nested)(nil), "grpcurl.test.NestedMessage.Nested")
	proto.RegisterType((*EnumMessage)(nil), "grpcurl.test.EnumMessage")
	proto.RegisterType((*OneofMessage)(nil), "grpcurl.test.OneofMessage")
	proto.RegisterType((*MapMessage)(nil), "grpcurl.test.MapMessage")
	proto.RegisterEnum("grpcurl.test.NumericEnum", NumericEnum_name, NumericEnum_value)
	proto.RegisterEnum("grpcurl.test.AliasedEnum", AliasedEnum_name, AliasedEnum_value)
	proto.RegisterEnum("grpcurl.test.EnumMessage_Nested", EnumMessage_Nested_name, EnumMessage_Nested_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Everything service

type EverythingClient interface {
	Simple(ctx context.Context, in *SimpleMessage, opts ...grpc.CallOption) (*SimpleMessage, error)
	Number(ctx context.Context, in *NumberMessage, opts ...grpc.CallOption) (*NumberMessage, error)
	Enum(ctx context.Context, in *EnumMessage, opts ...grpc.CallOption) (*EnumMessage, error)
	Oneof(ctx context.Context, in *OneofMessage, opts ...grpc.CallOption) (*OneofMessage, error)
	Map(ctx context.Context, in *MapMessage, opts ...grpc.CallOption) (*MapMessage, error)
}

type everythingClient struct {
	cc *grpc.ClientConn
}

func NewEverythingClient(cc *grpc.ClientConn) EverythingClient {
	return &everythingClient{cc}
}

func (c *everythingClient) Simple(ctx context.Context, in *SimpleMessage, opts ...grpc.CallOption) (*SimpleMessage, error) {
	out := new(SimpleMessage)
	err := grpc.Invoke(ctx, "/grpcurl.test.Everything/Simple", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *everythingClient) Number(ctx context.Context, in *NumberMessage, opts ...grpc.CallOption) (*NumberMessage, error) {
	out := new(NumberMessage)
	err := grpc.Invoke(ctx, "/grpcurl.test.Everything/Number", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *everythingClient) Enum(ctx context.Context, in *EnumMessage, opts ...grpc.CallOption) (*EnumMessage, error) {
	out := new(EnumMessage)
	err := grpc.Invoke(ctx, "/grpcurl.test.Everything/Enum", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *everythingClient) Oneof(ctx context.Context, in *OneofMessage, opts ...grpc.CallOption) (*OneofMessage, error) {
	out := new(OneofMessage)
	err := grpc.Invoke(ctx, "/grpcurl.test.Everything/Oneof", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *everythingClient) Map(ctx context.Context, in *MapMessage, opts ...grpc.CallOption) (*MapMessage, error) {
	out := new(MapMessage)
	err := grpc.Invoke(ctx, "/grpcurl.test.Everything/Map", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Everything service

type EverythingServer interface {
	Simple(context.Context, *SimpleMessage) (*SimpleMessage, error)
	Number(context.Context, *NumberMessage) (*NumberMessage, error)
	Enum(context.Context, *EnumMessage) (*EnumMessage, error)
	Oneof(context.Context, *OneofMessage) (*OneofMessage, error)
	Map(context.Context, *MapMessage) (*MapMessage, error)
}

func RegisterEverythingServer(s *grpc.Server, srv EverythingServer) {
	s.RegisterService(&_Everything_serviceDesc, srv)
}

func _Everything_Simple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EverythingServer).Simple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcurl.test.Everything/Simple",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EverythingServer).Simple(ctx, req.(*SimpleMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Everything_Number_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumberMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EverythingServer).Number(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcurl.test.Everything/Number",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EverythingServer).Number(ctx, req.(*NumberMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Everything_Enum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnumMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EverythingServer).Enum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcurl.test.Everything/Enum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EverythingServer).Enum(ctx, req.(*EnumMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Everything_Oneof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OneofMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EverythingServer).Oneof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcurl.test.Everything/Oneof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EverythingServer).Oneof(ctx, req.(*OneofMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Everything_Map_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EverythingServer).Map(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcurl.test.Everything/Map",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EverythingServer).Map(ctx, req.(*MapMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Everything_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcurl.test.Everything",
	HandlerType: (*EverythingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Simple",
			Handler:    _Everything_Simple_Handler,
		},
		{
			MethodName: "Number",
			Handler:    _Everything_Number_Handler,
		},
		{
			MethodName: "Enum",
			Handler:    _Everything_Enum_Handler,
		},
		{
			MethodName: "Oneof",
			Handler:    _Everything_Oneof_Handler,
		},
		{
			MethodName: "Map",
			Handler:    _Everything_Map_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "testdata/everything.proto",
}

func init() { proto.RegisterFile("testdata/everything.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 887 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x96, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0xc7, 0x45, 0xc9, 0x76, 0xe2, 0x23, 0xab, 0x55, 0xb8, 0xa2, 0x48, 0xd4, 0x0d, 0x55, 0x55,
	0x6c, 0xd0, 0x7a, 0x61, 0x23, 0x6e, 0x51, 0x14, 0x2b, 0x30, 0x20, 0x6d, 0x84, 0x76, 0x58, 0x2c,
	0x77, 0x4a, 0xda, 0x0e, 0xb9, 0x31, 0xe4, 0x98, 0x71, 0x85, 0x5a, 0x1f, 0xd0, 0x47, 0xb1, 0xec,
	0x39, 0xf6, 0x32, 0x7b, 0x93, 0xdd, 0xec, 0x55, 0x86, 0x41, 0xa2, 0x3e, 0x48, 0xf9, 0xa3, 0xb9,
	0x23, 0x0f, 0xff, 0xfc, 0x9d, 0x73, 0xc8, 0x73, 0x44, 0xc1, 0x51, 0x4a, 0x92, 0x74, 0xe1, 0xa6,
	0xee, 0x88, 0x7c, 0x21, 0xf1, 0x4d, 0xfa, 0xc9, 0x0b, 0x96, 0xc3, 0x28, 0x0e, 0xd3, 0x10, 0x0f,
	0x96, 0x71, 0x74, 0x95, 0xc5, 0xab, 0x61, 0x2e, 0x31, 0x7e, 0x03, 0xe5, 0xdc, 0xf3, 0xa3, 0x15,
	0x99, 0x90, 0x24, 0x71, 0x97, 0x04, 0x3f, 0x82, 0x41, 0x92, 0xc6, 0x5e, 0xb0, 0x9c, 0x7d, 0x71,
	0x57, 0x19, 0x39, 0x44, 0x3a, 0x32, 0xfb, 0x8e, 0x4c, 0x6d, 0x1f, 0x72, 0x13, 0xfe, 0x0e, 0x60,
	0x1e, 0x86, 0xab, 0x52, 0x20, 0xea, 0xc8, 0xdc, 0x77, 0xfa, 0xb9, 0xa5, 0x58, 0x36, 0xfe, 0x96,
	0x40, 0xb1, 0x33, 0x7f, 0x4e, 0xe2, 0x8a, 0xf9, 0x10, 0xe4, 0xeb, 0x55, 0xe8, 0xa6, 0x0c, 0x52,
	0x74, 0xa0, 0x30, 0x51, 0xe2, 0x23, 0x18, 0x2c, 0xc2, 0x6c, 0xbe, 0x22, 0x0c, 0x13, 0x39, 0x32,
	0xb5, 0x51, 0xc9, 0x43, 0x90, 0xbd, 0x20, 0x7d, 0x3a, 0x2e, 0x15, 0x92, 0x8e, 0xcc, 0xae, 0x03,
	0x85, 0x89, 0x15, 0x3c, 0x7f, 0x56, 0x0a, 0x3a, 0x3a, 0x32, 0xa5, 0x42, 0xf0, 0xfc, 0x59, 0xed,
	0x24, 0x63, 0x11, 0x5d, 0x1d, 0x99, 0x8a, 0x23, 0x67, 0x0c, 0xa3, 0x94, 0xd4, 0x90, 0x9e, 0x8e,
	0xcc, 0x0e, 0x95, 0x30, 0x94, 0x84, 0xa5, 0xec, 0xe9, 0xc8, 0x3c, 0x70, 0xe4, 0x84, 0xa7, 0x24,
	0x2c, 0x65, 0x5f, 0x47, 0x26, 0xa6, 0x92, 0x8a, 0xf2, 0x18, 0x94, 0x6b, 0xef, 0x0f, 0xb2, 0xa8,
	0x31, 0x7d, 0x1d, 0x99, 0x7b, 0xce, 0xa0, 0x34, 0xf2, 0xa2, 0x1a, 0x04, 0x3a, 0x32, 0x7b, 0xa5,
	0xa8, 0x22, 0x7d, 0x0f, 0x77, 0x12, 0x1e, 0x25, 0xeb, 0xc8, 0xbc, 0xeb, 0x28, 0x09, 0xc7, 0xaa,
	0x65, 0x35, 0x6c, 0xa0, 0x23, 0x53, 0xad, 0x64, 0x25, 0xcd, 0xf8, 0x0f, 0x81, 0x62, 0x93, 0x24,
	0x25, 0x8b, 0xea, 0xee, 0x2c, 0x18, 0x04, 0x85, 0x81, 0xb9, 0x3c, 0x79, 0x6c, 0x0c, 0xd9, 0x2a,
	0x1a, 0x72, 0x5b, 0xca, 0x99, 0x23, 0xd3, 0x7d, 0xd4, 0xff, 0xef, 0x70, 0x3f, 0x26, 0x11, 0x71,
	0x73, 0x10, 0xcb, 0x4b, 0x0e, 0x45, 0x5d, 0xba, 0x25, 0xf0, 0x5e, 0x45, 0xb0, 0x1b, 0x70, 0xa2,
	0x9d, 0x41, 0x8f, 0xce, 0xdb, 0x25, 0x82, 0xd6, 0x4a, 0xa4, 0x5d, 0xdb, 0xe2, 0x5a, 0x6d, 0x1b,
	0xff, 0x4a, 0x20, 0x5b, 0x41, 0xe6, 0x57, 0xe9, 0xbf, 0x01, 0x1c, 0x64, 0x3e, 0x89, 0xbd, 0xab,
	0x19, 0x09, 0x32, 0x9f, 0x41, 0xdf, 0x19, 0x1f, 0xb5, 0x62, 0xa6, 0xba, 0x7c, 0xb7, 0xa3, 0x06,
	0xcd, 0x84, 0xfa, 0xbe, 0x84, 0x6f, 0x9b, 0x03, 0x58, 0x23, 0xd2, 0x63, 0xd8, 0x89, 0x3c, 0xaa,
	0xb3, 0x6f, 0xa1, 0x93, 0x3c, 0x48, 0x77, 0xe5, 0xb9, 0x09, 0x59, 0xb0, 0x41, 0x4a, 0x9b, 0x82,
	0x3c, 0xa1, 0x3a, 0x1a, 0xa4, 0xdb, 0x4c, 0x68, 0x90, 0x67, 0x70, 0x50, 0x5e, 0x0e, 0xc3, 0xe9,
	0x14, 0x1c, 0x9d, 0xe7, 0x30, 0x67, 0x54, 0x5d, 0xcf, 0x5d, 0xba, 0xb5, 0xa1, 0xcd, 0xe0, 0x41,
	0xfb, 0xce, 0xd9, 0x8c, 0xbb, 0x45, 0xc6, 0x5f, 0xe7, 0x1e, 0xf2, 0xd7, 0xde, 0xe4, 0x6d, 0x1c,
	0xd7, 0x57, 0x2f, 0xc3, 0xde, 0x7b, 0xfb, 0x57, 0x7b, 0xfa, 0xd1, 0x56, 0x85, 0x7c, 0xf2, 0xce,
	0xb2, 0x4f, 0x7f, 0xb1, 0xdf, 0xa8, 0x08, 0x2b, 0xd0, 0x7f, 0x3d, 0x9d, 0xbc, 0x3b, 0xb3, 0x2e,
	0xac, 0x53, 0x55, 0x34, 0x08, 0x0c, 0xa6, 0x01, 0x09, 0xaf, 0x9b, 0xcf, 0xdd, 0x7a, 0xcd, 0xbc,
	0x15, 0xb8, 0xaa, 0x79, 0xbc, 0xa9, 0x6a, 0xde, 0x0a, 0x5c, 0xdd, 0xbc, 0x52, 0x40, 0x0e, 0x73,
	0x2e, 0xd5, 0x18, 0x7f, 0x75, 0x00, 0x26, 0x6e, 0x54, 0x79, 0x79, 0x0d, 0x7d, 0xdf, 0x8d, 0x6a,
	0x1f, 0x79, 0xc1, 0xff, 0xc0, 0xe7, 0xdd, 0x88, 0xf3, 0x61, 0xc1, 0xb4, 0x82, 0x34, 0xbe, 0x71,
	0xf6, 0xfd, 0x72, 0x8a, 0x67, 0xf0, 0x8d, 0xef, 0x46, 0x11, 0x59, 0xcc, 0x5a, 0xe1, 0xe4, 0xb8,
	0xd1, 0x2e, 0x5c, 0x44, 0x16, 0xe7, 0x4d, 0xac, 0x94, 0x7b, 0xe0, 0xb7, 0xed, 0x8c, 0x03, 0xae,
	0xe3, 0xa5, 0x5b, 0x39, 0x60, 0x7a, 0x92, 0x73, 0xc0, 0xd8, 0xb5, 0x0f, 0xa0, 0x70, 0xc9, 0x61,
	0x15, 0xa4, 0xcf, 0xe4, 0xa6, 0x7c, 0x63, 0xf2, 0x21, 0x1e, 0x41, 0xb7, 0x39, 0xe5, 0x9d, 0xfd,
	0x40, 0x75, 0x3f, 0x89, 0x2f, 0x90, 0x76, 0x0a, 0xf7, 0x37, 0x67, 0xb9, 0xc1, 0xc1, 0x3d, 0xd6,
	0x41, 0x9f, 0xa5, 0xb8, 0x15, 0xa5, 0x9d, 0xca, 0x06, 0xca, 0x31, 0x4b, 0x91, 0xc7, 0x0f, 0x76,
	0x7c, 0xbd, 0x18, 0x17, 0x4f, 0x7e, 0x04, 0x99, 0x49, 0x01, 0xef, 0x43, 0xe7, 0xd2, 0x72, 0xa6,
	0xaa, 0x80, 0xf7, 0x40, 0x9a, 0xda, 0x96, 0x8a, 0xf2, 0xc1, 0xc5, 0xc7, 0xa9, 0x2a, 0x3e, 0x79,
	0x01, 0x32, 0xd3, 0xab, 0x6b, 0x05, 0x7e, 0x7e, 0x71, 0xe2, 0xe4, 0x15, 0x8d, 0xf2, 0x89, 0xf3,
	0xde, 0xb6, 0x8b, 0x6a, 0xd7, 0x44, 0x15, 0x8d, 0xff, 0x11, 0x01, 0xac, 0xfa, 0xd5, 0xc7, 0xa7,
	0xd0, 0xa3, 0x2f, 0x3c, 0x6e, 0x45, 0xc9, 0xbd, 0xfb, 0xda, 0xae, 0x45, 0x43, 0xc8, 0x29, 0xf4,
	0x4d, 0x6f, 0x53, 0xb8, 0x97, 0x5e, 0xdb, 0xb5, 0x68, 0x08, 0xf8, 0x67, 0xe8, 0x14, 0xd9, 0x1c,
	0x6d, 0x6d, 0x7a, 0x6d, 0xfb, 0x92, 0x21, 0xe0, 0x13, 0xe8, 0x16, 0xdd, 0x8b, 0x35, 0x5e, 0xc5,
	0xb6, 0xb4, 0xb6, 0x63, 0xcd, 0x10, 0xf0, 0x4b, 0x90, 0x26, 0x6e, 0x84, 0x0f, 0xb7, 0x95, 0xb3,
	0xb6, 0x75, 0xc5, 0x10, 0x5e, 0x1d, 0x5f, 0x8e, 0x96, 0x5e, 0xfa, 0x29, 0x9b, 0x0f, 0xaf, 0x42,
	0x7f, 0xf4, 0xd9, 0xfd, 0x93, 0x2c, 0xb3, 0x24, 0x8b, 0xbd, 0x51, 0xb9, 0x65, 0x54, 0xfd, 0x76,
	0xbd, 0xac, 0x06, 0xf3, 0x5e, 0xf1, 0xd7, 0xf5, 0xf4, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x59,
	0xd4, 0x0e, 0x0c, 0x92, 0x09, 0x00, 0x00,
}
